<a href="https://colab.research.google.com/github/eeolga/deep/blob/main/Logs_CAD_4_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

In [ ]:
import csv

In [ ]:
logs_path="/content/logs_4.csv"

In [ ]:
logsq_numpy = np.loadtxt(logs_path, dtype=np.float32,delimiter=";", skiprows=1)

In [ ]:
logsq_numpy

array([[2.9292e+04, 1.0000e+00, 1.0000e+00, 0.0000e+00, 2.0000e+01,
        2.3000e+01, 3.0000e+00, 1.0000e+00, 5.0000e+00],
       [2.6864e+04, 2.0000e+00, 0.0000e+00, 1.0000e+00,        nan,
        7.0000e+00, 3.0000e+00, 0.0000e+00, 0.0000e+00],
       [2.6861e+04, 2.0000e+00, 0.0000e+00, 1.0000e+00, 2.1000e+01,
        1.8000e+01, 1.0000e+00, 1.0000e+00, 3.0000e+00],
       [2.6760e+04, 3.0000e+00, 1.0000e+00, 0.0000e+00,        nan,
        8.0000e+00, 1.0000e+00, 1.0000e+00, 5.0000e+00],
       [2.6544e+04, 4.0000e+00, 1.0000e+00, 1.0000e+00, 2.1000e+01,
        9.0000e+00, 1.0000e+00, 1.0000e+00, 5.0000e+00],
       [2.9598e+04, 1.1000e+01, 1.0000e+00, 1.0000e+00, 2.5000e+01,
        7.0000e+00, 1.0000e+00, 1.0000e+00, 0.0000e+00],
       [2.9133e+04, 1.0000e+00, 1.0000e+00, 1.0000e+00, 2.0000e+01,
        1.4000e+01, 1.0000e+00, 1.0000e+00, 5.0000e+00],
       [2.6604e+04, 2.0000e+00, 0.0000e+00, 1.0000e+00, 2.3000e+01,
        6.0000e+00, 1.0000e+00, 1.0000e+00, 4.0000e+00],


In [ ]:
col_list = next(csv.reader(open(logs_path), delimiter=';'))

In [ ]:
logsq_numpy.shape, col_list

((17, 9),
 ['\ufeffID',
  'Spec',
  'MotherTongue',
  'Gender',
  'Age',
  'Activity',
  'DayPart',
  'Lesson',
  'Grade'])

In [ ]:
logsq = torch.from_numpy(logsq_numpy)

In [ ]:
logsq.shape, logsq.dtype

(torch.Size([17, 9]), torch.float32)

In [ ]:
data = logsq[:, :-1]  #select all rows and colomns exept the last

In [ ]:
data, data.shape

(tensor([[2.9292e+04, 1.0000e+00, 1.0000e+00, 0.0000e+00, 2.0000e+01, 2.3000e+01,
          3.0000e+00, 1.0000e+00],
         [2.6864e+04, 2.0000e+00, 0.0000e+00, 1.0000e+00,        nan, 7.0000e+00,
          3.0000e+00, 0.0000e+00],
         [2.6861e+04, 2.0000e+00, 0.0000e+00, 1.0000e+00, 2.1000e+01, 1.8000e+01,
          1.0000e+00, 1.0000e+00],
         [2.6760e+04, 3.0000e+00, 1.0000e+00, 0.0000e+00,        nan, 8.0000e+00,
          1.0000e+00, 1.0000e+00],
         [2.6544e+04, 4.0000e+00, 1.0000e+00, 1.0000e+00, 2.1000e+01, 9.0000e+00,
          1.0000e+00, 1.0000e+00],
         [2.9598e+04, 1.1000e+01, 1.0000e+00, 1.0000e+00, 2.5000e+01, 7.0000e+00,
          1.0000e+00, 1.0000e+00],
         [2.9133e+04, 1.0000e+00, 1.0000e+00, 1.0000e+00, 2.0000e+01, 1.4000e+01,
          1.0000e+00, 1.0000e+00],
         [2.6604e+04, 2.0000e+00, 0.0000e+00, 1.0000e+00, 2.3000e+01, 6.0000e+00,
          1.0000e+00, 1.0000e+00],
         [2.9346e+04, 1.0000e+00, 1.0000e+00, 1.0000e+00, 2.0000

In [ ]:
target = logsq[:, -1]  #select all rows

In [ ]:
target, target.shape

(tensor([5., 0., 3., 5., 5., 0., 5., 4., 5., 4., 0., 0., 4., 4., 4., 5., 0.]),
 torch.Size([17]))

In [ ]:
target = logsq[:, -1] .long() #labels as an integrated vector

In [ ]:
target

tensor([5, 0, 3, 5, 5, 0, 5, 4, 5, 4, 0, 0, 4, 4, 4, 5, 0])

In [ ]:
target_onehot = torch.zeros(target.shape[0], 6) #score  1* (1,0,0,0,0,0) score  5* (0,0,0,0,0,1)
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

tensor([[0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0.]])

In [ ]:
target_unsqueezed = target.unsqueeze(1)

In [ ]:
target_unsqueezed

tensor([[5],
        [0],
        [3],
        [5],
        [5],
        [0],
        [5],
        [4],
        [5],
        [4],
        [0],
        [0],
        [4],
        [4],
        [4],
        [5],
        [0]])

In [ ]:
data_mean =torch.mean(data, dim=0) #Categorizing
data_mean

tensor([2.7802e+04, 2.7059e+00, 7.6471e-01, 8.2353e-01,        nan, 1.0235e+01,
        1.5882e+00, 7.6471e-01])

In [ ]:
data_var=torch.var(data, dim=0)
data_var

tensor([3.0928e+06, 6.0956e+00, 1.9118e-01, 1.5441e-01,        nan, 2.6691e+01,
        7.5735e-01, 1.9118e-01])

In [ ]:
data_normalized= (data - data_mean) / torch.sqrt(data_var)  #data normalization
data_normalized

tensor([[ 0.8474, -0.6909,  0.5381, -2.0957,     nan,  2.4707,  1.6222,  0.5381],
        [-0.5332, -0.2859, -1.7489,  0.4491,     nan, -0.6262,  1.6222, -1.7489],
        [-0.5349, -0.2859, -1.7489,  0.4491,     nan,  1.5029, -0.6759,  0.5381],
        [-0.5923,  0.1191,  0.5381, -2.0957,     nan, -0.4327, -0.6759,  0.5381],
        [-0.7151,  0.5242,  0.5381,  0.4491,     nan, -0.2391, -0.6759,  0.5381],
        [ 1.0214,  3.3594,  0.5381,  0.4491,     nan, -0.6262, -0.6759,  0.5381],
        [ 0.7570, -0.6909,  0.5381,  0.4491,     nan,  0.7287, -0.6759,  0.5381],
        [-0.6810, -0.2859, -1.7489,  0.4491,     nan, -0.8198, -0.6759,  0.5381],
        [ 0.8781, -0.6909,  0.5381,  0.4491,     nan, -1.2069, -0.6759,  0.5381],
        [-0.7043,  0.5242,  0.5381,  0.4491,     nan,  0.7287, -0.6759,  0.5381],
        [-0.6776,  0.5242,  0.5381,  0.4491,     nan, -0.6262, -0.6759,  0.5381],
        [-0.5758,  0.1191,  0.5381,  0.4491,     nan,  0.3416,  0.4732, -1.7489],
        [ 1.0703

In [ ]:
bad_indexes = target <= 3
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([17]), torch.bool, tensor(6))

In [ ]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([6, 8])

In [ ]:
bad_data - data[target <= 3]
mid_data = data [ (target > 3) & (target < 5)]
good_data = data[target >= 4]

In [ ]:
bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim= 0)
good_mean = torch.mean(good_data, dim= 0)

In [ ]:
for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
  print('{:5} {:17} {:7.6f} {:7.6f} {:7.6f}'.format(i, *args))

    0 ID               26713.333984 28384.599609 28395.273438
    1 Spec              4.333333 1.800000 1.818182
    2 MotherTongue      0.666667 0.600000 0.818182
    3 Gender            0.833333 1.000000 0.818182
    4 Age                   nan     nan     nan
    5 Activity          9.666667 10.400000 10.545455
    6 DayPart           1.833333 1.600000 1.454545
    7 Lesson            0.500000 0.800000 0.909091


In [ ]:
Activity_threshold = 10.54
Activity_data = data[:,7]

In [ ]:
predicted_indexes = torch.lt(Activity_data,Activity_threshold)

In [ ]:
predicted_indexes.shape, predicted_indexes.dtype,
predicted_indexes.sum()

tensor(17)

In [ ]:
actual_indexes = target > 3
actual_indexes.shape, actual_indexes.dtype,
actual_indexes.sum()

tensor(11)

In [ ]:
n_matches = torch.sum(actual_indexes &predicted_indexes) .item()

In [ ]:
n_predicted = torch.sum(predicted_indexes) .item()
n_actual = torch.sum(actual_indexes) .item()
n_matches, n_matches / n_predicted, n_matches / n_actual

(11, 0.6470588235294118, 1.0)