<a href="https://colab.research.google.com/github/eeolga/deep/blob/main/Working_with_logs_data_(CSV).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Working with tabular data (CSV)

In [1]:
import numpy as np
import torch

In [2]:
import csv

In [7]:
CAD_path = "/content/logs_4_csv.csv"

In [8]:
CADq_numpy = np.loadtxt(CAD_path, dtype=np.float32,delimiter=";", skiprows=1)

In [ ]:
CADq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [9]:
col_list = next(csv.reader(open(CAD_path), delimiter=';'))

In [10]:
CADq_numpy.shape, col_list

((17, 9),
 ['\ufeffID',
  'Spec',
  'MotherTongue',
  'Gender',
  'Age',
  'Activity',
  'DayPart',
  'Lesson',
  'Grade'])

In [11]:
CADq = torch.from_numpy(CADq_numpy)

In [12]:
CADq.shape, CADq.dtype

(torch.Size([17, 9]), torch.float32)

*Score*  with label

In [13]:
data = CADq[:, :-1]  #select all rows and colomns exept the last

In [14]:
data, data.shape

(tensor([[2.9292e+04, 1.0000e+00, 1.0000e+00, 0.0000e+00, 2.0000e+01, 2.3000e+01,
          3.0000e+00, 1.0000e+00],
         [2.6864e+04, 2.0000e+00, 0.0000e+00, 1.0000e+00,        nan, 7.0000e+00,
          3.0000e+00, 0.0000e+00],
         [2.6861e+04, 2.0000e+00, 0.0000e+00, 1.0000e+00, 2.1000e+01, 1.8000e+01,
          1.0000e+00, 1.0000e+00],
         [2.6760e+04, 3.0000e+00, 1.0000e+00, 0.0000e+00,        nan, 8.0000e+00,
          1.0000e+00, 1.0000e+00],
         [2.6544e+04, 4.0000e+00, 1.0000e+00, 1.0000e+00, 2.1000e+01, 9.0000e+00,
          1.0000e+00, 1.0000e+00],
         [2.9598e+04, 1.1000e+01, 1.0000e+00, 1.0000e+00, 2.5000e+01, 7.0000e+00,
          1.0000e+00, 1.0000e+00],
         [2.9133e+04, 1.0000e+00, 1.0000e+00, 1.0000e+00, 2.0000e+01, 1.4000e+01,
          1.0000e+00, 1.0000e+00],
         [2.6604e+04, 2.0000e+00, 0.0000e+00, 1.0000e+00, 2.3000e+01, 6.0000e+00,
          1.0000e+00, 1.0000e+00],
         [2.9346e+04, 1.0000e+00, 1.0000e+00, 1.0000e+00, 2.0000

In [15]:
target = CADq[:, -1]  #select all rows and the last!

In [16]:
target, target.shape

(tensor([5., 0., 3., 5., 5., 0., 5., 4., 5., 4., 0., 0., 4., 4., 4., 5., 0.]),
 torch.Size([17]))

labels as an integrated vector

In [17]:
target = CADq[:, -1] .long()

In [18]:
target

tensor([5, 0, 3, 5, 5, 0, 5, 4, 5, 4, 0, 0, 4, 4, 4, 5, 0])

score  1* (1,0,0,0,0,0,0,0),        score 5* (0,0,0,0,1,0,0,0)

In [49]:
target_onehot = torch.zeros(target.shape[0], 8)
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

tensor([[0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
target_unsqueezed = target.unsqueeze(1)

In [51]:
target_unsqueezed

tensor([[5],
        [0],
        [3],
        [5],
        [5],
        [0],
        [5],
        [4],
        [5],
        [4],
        [0],
        [0],
        [4],
        [4],
        [4],
        [5],
        [0]])

Categorizing

In [52]:
data_mean =torch.mean(data, dim=0)
data_mean

tensor([2.7802e+04, 2.7059e+00, 7.6471e-01, 8.2353e-01,        nan, 1.0235e+01,
        1.5882e+00, 7.6471e-01])

In [53]:
data_var=torch.var(data, dim=0)
data_var

tensor([3.0928e+06, 6.0956e+00, 1.9118e-01, 1.5441e-01,        nan, 2.6691e+01,
        7.5735e-01, 1.9118e-01])

In [54]:
data_normalized= (data - data_mean) / torch.sqrt(data_var)  #data normalization
data_normalized

tensor([[ 0.8474, -0.6909,  0.5381, -2.0957,     nan,  2.4707,  1.6222,  0.5381],
        [-0.5332, -0.2859, -1.7489,  0.4491,     nan, -0.6262,  1.6222, -1.7489],
        [-0.5349, -0.2859, -1.7489,  0.4491,     nan,  1.5029, -0.6759,  0.5381],
        [-0.5923,  0.1191,  0.5381, -2.0957,     nan, -0.4327, -0.6759,  0.5381],
        [-0.7151,  0.5242,  0.5381,  0.4491,     nan, -0.2391, -0.6759,  0.5381],
        [ 1.0214,  3.3594,  0.5381,  0.4491,     nan, -0.6262, -0.6759,  0.5381],
        [ 0.7570, -0.6909,  0.5381,  0.4491,     nan,  0.7287, -0.6759,  0.5381],
        [-0.6810, -0.2859, -1.7489,  0.4491,     nan, -0.8198, -0.6759,  0.5381],
        [ 0.8781, -0.6909,  0.5381,  0.4491,     nan, -1.2069, -0.6759,  0.5381],
        [-0.7043,  0.5242,  0.5381,  0.4491,     nan,  0.7287, -0.6759,  0.5381],
        [-0.6776,  0.5242,  0.5381,  0.4491,     nan, -0.6262, -0.6759,  0.5381],
        [-0.5758,  0.1191,  0.5381,  0.4491,     nan,  0.3416,  0.4732, -1.7489],
        [ 1.0703

Finding thresholds

In [55]:
bad_indexes = target <= 3
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([17]), torch.bool, tensor(6))

In [56]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([6, 8])

In [57]:
bad_data - data[target <= 3]
mid_data = data [ (target > 3) & (target < 5)]
good_data = data[target >= 5]

In [58]:
bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim= 0)
good_mean = torch.mean(good_data, dim= 0)

In [59]:
for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
  print('{:2} {:17} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

 0 ID               26713.33 28384.60 28404.17
 1 Spec                4.33   1.80   1.83
 2 MotherTongue        0.67   0.60   1.00
 3 Gender              0.83   1.00   0.67
 4 Age                  nan    nan    nan
 5 Activity            9.67  10.40  10.67
 6 DayPart             1.83   1.60   1.33
 7 Lesson              0.50   0.80   1.00


In [60]:
total_Activity_threshold = 10.40
total_Activity_data = data[:,6]

In [61]:
predicted_indexes = torch.lt(total_Activity_data,total_Activity_threshold)

In [62]:
predicted_indexes.shape, predicted_indexes.dtype,
predicted_indexes.sum()

tensor(17)

In [63]:
actual_indexes = target > 3
actual_indexes.shape, actual_indexes.dtype,
actual_indexes.sum()

tensor(11)

In [64]:
n_matches = torch.sum(actual_indexes &predicted_indexes) .item()

In [65]:
n_predicted = torch.sum(predicted_indexes) .item()
n_actual = torch.sum(actual_indexes) .item()
n_matches, n_matches / n_predicted, n_matches / n_actual

(11, 0.6470588235294118, 1.0)